name: Code Quality

on:
  push:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
          pip install pylint flake8 black pytest

      - name: Run Pylint
        run: |
          pylint src/

      - name: Run Flake8
        run: |
          flake8 src/

      - name: Run Black
        run: |
          black --check src/

      - name: Run unit tests
        run: |
          pytest tests/
      
      - name: Send email notification
        if: always()  # Send email even if previous steps fail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "GitHub Actions: ${{ github.workflow }} - ${{ job.status }}"
          body: |
            Workflow: ${{ github.workflow }}
            Status: ${{ job.status }}
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: larg8med@gmail.com  # Replace with your email address
          from: GitHub Actions larg8med@gmail.com  # Replace with your email address